spring:
  application:
    name: spring-boot-jpa-app

  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/training
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
