spring:
  application:
    name: math-client-api
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"


